root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:  
    docs/using-mobile-extensions/adobe-edge-consent: https://aep-sdks.gitbook.io/docs/consent-for-edge-network
