root: ./docs/v/

structure:  
    readme: README.md  
    summary: SUMMARY.md
    
redirects:  
    docs/v/AEP-Edge-Docs/experience-platform-extension: docs/release-notes
    docs/v/AEP-Edge-Docs/using-mobile-extensions/adobe-edge-consent: docs/foundation-extensions/consent-for-edge-network
